config/routes.rb
class DomainConstraint
  def initialize(domain)
    @domains = [domain].flatten
  end

  def matches?(request)
    @domains.include? request.domain
  end
end

Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  constraints DomainConstraint.new(['rawsme.local', 'raws.me']) do
    get "/:id" => "shortened_links#show"
  end

  root   'jobs#index'

  get 'health_check'                      => 'health_check#index', :as => :health_check

  resources :jobs do
    member do
      get   :preview
      post  :post
      patch :pause
    end
  end
  get    '/tags/:tags'                    => 'jobs#index',     as: :tag

  post   '/alerts'                        => 'alerts#create'
  delete '/alerts/:id'                    => 'alerts#destroy', as: :alert
  get    '/alerts/new'                    => 'alerts#new'
  get    '/alerts/tags/:tags/new'         => 'alerts#new'

  get    '/unsubscribe/:token'            => 'email_addresses#unsubscribe', as: :unsubscribe

  get    '/about'                         => 'pages#about', as: :about
  get    '/why'                           => 'pages#why', as: :why

  resources :email_addresses do
    get :validate
  end
  resources :filter_tags
  resources :users
  resource  :session
  resources :password_resets
  resources :validations

  namespace :admin do
    resources :jobs
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                    :integer          not null, primary key
#  created_at            :datetime
#  updated_at            :datetime
#  category_id           :integer
#  title                 :string           not null
#  posted_at             :datetime
#  company               :string           not null
#  location              :string           not null
#  description           :text             not null
#  company_url           :string
#  original_post_url     :string
#  source                :string
#  slug                  :string
#  type                  :string
#  sent_daily_alerts_at  :datetime
#  sent_weekly_alerts_at :datetime
#  last_tweeted_at       :datetime
#  tags                  :text             default([]), is an Array
#  company_description   :text
#  how_to_apply          :text
#  user_id               :uuid
#  expires_at            :datetime
#  status                :string
#  reviewed_at           :datetime
#  expired_at            :datetime
#  tsv                   :tsvector
#

class Job < ActiveRecord::Base
  include FriendlyId
  include PgSearch
  include AASM
  friendly_id :name_for_slug, use: :slugged

  validates_presence_of :title
  validates_presence_of :company
  validates_presence_of :description

  belongs_to :user

  attr_accessor :category

  scope :unsent_daily, ->() { where(sent_daily_alerts_at: nil) }
  scope :next_up_for_tweet, -> { where("posted_at > ?", 7.days.ago).posted.order('last_tweeted_at DESC') }
  scope :featured, ->() { where(type: 'Job::RemotelyAwesome') }
  scope :not_featured, ->() { where("type <> 'Job::RemotelyAwesome'") }
  scope :not_ours, ->() { where("type <> 'Job::RemotelyAwesome'") }
  scope :ours, ->() { where("type = 'Job::RemotelyAwesome'") }
  scope :today, ->() { where("posted_at >= NOW() - '1 day'::INTERVAL") }
  scope :before_today, ->() { where("posted_at < NOW() - '1 day'::INTERVAL") }
  scope :this_week, ->() { where("posted_at > NOW() - '1 week'::INTERVAL") }
  scope :should_be_expired, ->() { where("expires_at < NOW()") }
  scope :expires_tomorrow, ->() { where("expires_at > NOW() AND expires_at < NOW() + '1 day'::INTERVAL") }
  scope :for_tags, ->(tags) {
    return where('1=1') if tags.blank?
    tags_pg = "{#{tags.join(',')}}"
    where("tags @> ?", tags_pg)
  }
  scope :similar, ->(job, number=3) {
    category = job.category
    language = job.tags_that_are('language').first
    Job.for_tags([category, language]).where('id != ?', job.id).limit(number)
  }

  pg_search_scope :search, against: [:title, :company, :description], using: { tsearch: { tsvector_column: "tsv" } }

  # pseudo-scope. Using a class method instead because we need to override this in a child class.
  def self.probable_duplicate(other_job)
    at = other_job.posted_at
    sql = <<-SQL
        title ILIKE ?
    AND company ILIKE ?
    AND (
          ((posted_at - ?) < INTERVAL '14 DAYS' AND (posted_at - ?) >= '0 SECONDS') OR
          ((posted_at - ?) > INTERVAL '-14 DAYS' AND (posted_at - ?) <= '0 SECONDS')
        )
    SQL
    where(sql, other_job.title, other_job.company, at, at, at, at)
  end

  aasm column: 'status' do
    state :pending, initial: true
    state :paused
    state :posted
    state :expired
    state :dead

    event :post do
      before do
        touch(:posted_at) if posted_at.nil?
        update_attribute(:expires_at, Time.zone.now + 30.days)
      end
      transitions from: [:pending, :paused], to: :posted
      after do
        send_notice if self.respond_to?(:send_notice)
      end
    end

    event :pause do
      transitions from: [:pending, :posted], to: :paused
    end

    event :kill do
      transitions from: [:posted], to: :dead
    end

    event :expire do
      before do
        touch(:expired_at)
      end
      transitions from: [:pending, :posted], to: :expired
    end
  end

  def name_for_slug
    "#{self.company} #{self.title}"
  end

  def fetch_description!(url, tags=%w[div p ul li strong h2], strip=%w[img])
    begin
      self.description = BasicDescriptionScraper.scrape(url,tags,strip)
    rescue => e
      Rails.logger.error "Failed to process job description for #{url} : #{e.message}"
      Rails.logger.error e.backtrace.join("\n ")
    end
  end

  def rebuild_tags!(category, other=nil)
    tags = TagBuilder.new(category, self.title, self.description, other).tags
    self.tags = tags[:all]
  end

  def grouped_tags
    language_tags = (self.tags & TagBuilder::LANGUAGE_TAGS)
    library_tags = (self.tags & TagBuilder::LIBRARY_TAGS)
    tool_tags = (self.tags & TagBuilder::TOOL_TAGS)
    skill_tags = (self.tags & TagBuilder::SKILL_TAGS)
    language_tags + library_tags + tool_tags + skill_tags
  end

  def category
    (tags && TagBuilder::CATEGORY_TAGS).first
  end

  def tags_that_are(type)
    tags && TagBuilder.const_get("#{type.upcase}_TAGS")
  end

  def reviewed?
    reviewed_at.present?
  end

  def reviewed!
    touch(:reviewed_at)
  end

  def ours?
    source == 'Remotely Awesome Jobs'
  end

  def self.skip_description_scrape?
    false
  end
end

app/models/job/angellist.rb
# == Schema Information
#
# Table name: jobs
#
#  id                    :integer          not null, primary key
#  created_at            :datetime
#  updated_at            :datetime
#  category_id           :integer
#  title                 :string           not null
#  posted_at             :datetime
#  company               :string           not null
#  location              :string           not null
#  description           :text             not null
#  company_url           :string
#  original_post_url     :string
#  source                :string
#  slug                  :string
#  type                  :string
#  sent_daily_alerts_at  :datetime
#  sent_weekly_alerts_at :datetime
#  last_tweeted_at       :datetime
#  tags                  :text             default([]), is an Array
#  company_description   :text
#  how_to_apply          :text
#  user_id               :uuid
#  expires_at            :datetime
#  status                :string
#  reviewed_at           :datetime
#  expired_at            :datetime
#  tsv                   :tsvector
#

class Job::Angellist < Job
  class << self
    def factory(entry, opts={})
      parent = opts[:parent]
      company = parent.css('a.startup-link').text
      location = parent.css('div.tag.locations').text
      summary = parent.css('div.content div.description').text
      website = parent.css('a.website-link').attr('href')      
      title = entry.css('.title a[target=_blank]').text
      original_post_url = entry.css('.title a[target=_blank]').attr('href')
      original_tags = entry.css('.tags').text
      if company && title && location && original_post_url
        job = self.new(title: title.strip,
                       posted_at: Time.zone.now,
                       company: company.strip,
                       location: location.strip,
                       description: summary,
                       company_url: website,
                       original_post_url: original_post_url,
                       source: "AngelList")
        category = CategoryGuesser.guess_category_from_title(title)
        job.rebuild_tags!(category, original_tags)
        return job
      end
    end
  end
end

app/models/job/authentic.rb
# == Schema Information
#
# Table name: jobs
#
#  id                    :integer          not null, primary key
#  created_at            :datetime
#  updated_at            :datetime
#  category_id           :integer
#  title                 :string           not null
#  posted_at             :datetime
#  company               :string           not null
#  location              :string           not null
#  description           :text             not null
#  company_url           :string
#  original_post_url     :string
#  source                :string
#  slug                  :string
#  type                  :string
#  sent_daily_alerts_at  :datetime
#  sent_weekly_alerts_at :datetime
#  last_tweeted_at       :datetime
#  tags                  :text             default([]), is an Array
#  company_description   :text
#  how_to_apply          :text
#  user_id               :uuid
#  expires_at            :datetime
#  status                :string
#  reviewed_at           :datetime
#  expired_at            :datetime
#  tsv                   :tsvector
#

class Job::Authentic < Job
  CATEGORIES =
    { '1' => 'other',
      '2' => 'development',
      '3' => 'design',
      '4' => 'development',
      '5' => 'development',
      '6' => 'management',
      '7' => 'design',
      '8' => 'other',
      '9' => 'other' }

  class << self
    def feed_urls
      CATEGORIES.keys.map { |cat| "http://www.authenticjobs.com/rss/custom.php?terms=&type=1,2,3,4,5,6,7&cats=#{cat}&onlyremote=1&location=" }
    end

  
    def factory(entry, feed, opts={})
      company, title = entry.title.split(': ')
      location = entry.summary.match(/.*?<strong>\((.*?)\)<\/strong>/)[1]
      job = self.new(title: title,
                     posted_at: entry.published,
                     company: company,
                     location: location,
                     description: entry.summary,
                     company_url: '',
                     original_post_url: entry.entry_id.gsub(/^http:/, 'https:'),
                     source: "Authentic Jobs")
      category = determine_category(feed)
      job.rebuild_tags!(category)
      return job
    end

    def determine_category(feed)
      CATEGORIES[feed.feed_url.match(/.*?cats=([0-9]).*/)[1]]
    end
  end

  def fetch_description!(url)
    rss_description = self.description
    parsed = rss_description.match(/<p>(.*?)<\/p>.*?<strong>\((.*?)\)<\/strong>.*/)
    self.description.gsub!(/.*?<strong>\((.*?)\)<\/strong>.*/, "<p>Job Type: <b>#{parsed[1]}</b><br/>Location: <b>#{parsed[2]}</b></p>")
  end  
end

app/models/job/remotely_awesome.rb
# == Schema Information
#
# Table name: jobs
#
#  id                    :integer          not null, primary key
#  created_at            :datetime
#  updated_at            :datetime
#  category_id           :integer
#  title                 :string           not null
#  posted_at             :datetime
#  company               :string           not null
#  location              :string           not null
#  description           :text             not null
#  company_url           :string
#  original_post_url     :string
#  source                :string
#  slug                  :string
#  type                  :string
#  sent_daily_alerts_at  :datetime
#  sent_weekly_alerts_at :datetime
#  last_tweeted_at       :datetime
#  tags                  :text             default([]), is an Array
#  company_description   :text
#  how_to_apply          :text
#  user_id               :uuid
#  expires_at            :datetime
#  status                :string
#  reviewed_at           :datetime
#  expired_at            :datetime
#  tsv                   :tsvector
#

class Job::RemotelyAwesome < Job
  belongs_to :user
  after_initialize :init
  
  def init
    self.source = 'Remotely Awesome Jobs'
  end

  def send_notice
    NoticeMailer.new_job_posted(self.id).deliver_later(queue: :low)
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  def index
    @q = params[:q]
    query = Job.all.order('posted_at DESC')
    query = query.search(@q) if @q.present?
    @jobs = query.page(params[:page] || 1).per(50)
  end

  def edit
    @job = Job.friendly.find(params[:id])
    @job.reviewed!
  end

  def update
    @job = Job.friendly.find(params[:id])
    if @job && @job.update_attributes(job_params)
      redirect_to admin_jobs_path, notice: "Job updated"
    else
      flash[:error] = "Unable to update job post: #{@job.errors.full_messages.to_sentence}"
      render :edit      
    end
  end

  def destroy
    @job = Job.friendly.find(params[:id])
    @job.expire!
    redirect_to admin_jobs_path, notice: "Job expired"
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :category, :how_to_apply, :company, :location, :company_url, :company_description, :tags => [])
  end
end

app/controllers/jobs_controller.rb
# -*- coding: utf-8 -*-
class JobsController < ApplicationController
  def index
    @tags = (params[:tags] || '').split('+')
    @q = params[:q]
    query = Job.posted.for_tags(@tags).order('posted_at DESC')
    query = query.search(@q) if @q.present?

    @featured = query.featured
    @today = query.not_featured.today.page(params[:page] || 1)
    @jobs = query.not_featured.before_today.page(params[:page] || 1)

    respond_to do |format|
      format.html { render 'index', layout: 'listings' }
      format.js
    end
  end

  def show
    @job = Job.friendly.find(params[:id])
    render_404 and return unless @job.posted?
  end

  def new
    defaults = current_user.defaults_from_previous_job if logged_in?
    @job = Job::RemotelyAwesome.new(defaults)
    @job.user = current_user || User.new
  end

  def edit
    @job = Job.friendly.find(params[:id])
  end

  def create
    @job = Job::RemotelyAwesome.new(job_params)
    render :new and return unless handle_user(user_params)
    @job.user = @user
    if @job.save
      redirect_to preview_job_path(@job)
    else
      flash[:error] = "Unable to create job post: #{@job.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def update
    @job = Job.where(user_id: current_user.id).friendly.find(params[:id])
    render :edit and return unless handle_user(user_params)
    if @job && @job.update_attributes(job_params)
      if @job.posted?
        redirect_to user_path(current_user), notice: 'Your job post has been updated.'
      else
        redirect_to preview_job_path(@job)
      end
    else
      flash[:error] = "Unable to update job post: #{@job.errors.full_messages.to_sentence}"
      render :edit
    end
  end

  def destroy
    @job = Job.where(user_id: current_user.id).friendly.find(params[:id])
    if @job && @job.destroy!
      flash[:notice] = "The job posting for '#{@job.title}' has been deleted."
    else
      flash[:error] = "There was an error deleting the job posting for '#{@job.title}': #{@job.errors.full_messages.to_sentence}"
    end
    redirect_to user_path(current_user)
  end

  def preview
    @job = Job.where(user_id: current_user.id).friendly.find(params[:id])
  end

  def post
    @job = Job.where(user_id: current_user.id).friendly.find(params[:id])
    if @job.user.email_validated?
      @job.post!
      flash[:notice] = "Your job has been posted."
    end
    redirect_to user_path(current_user)
  end

  def pause
    @job = Job.where(user_id: current_user.id).friendly.find(params[:id])
    @job.pause!
    redirect_to user_path(current_user)
  end


  private

  def handle_user(user_params)
    if logged_in?
      @user = current_user
      return true
    end
    if params[:account] == 'new'
      create_user(user_params)
    elsif params[:account] == 'existing'
      authenticate_user(user_params)
    end
  end

  def create_user(user_params)
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
    else
      flash[:error] = "Invalid user information: #{@user.errors.full_messages.to_sentence}"
      false
    end
  end

  def authenticate_user(user_params)
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      sign_in(@user)
    else
      flash[:error] = 'Bad email / password combination.'
      false
    end
  end

  def job_params
    params.require(:job_remotely_awesome).permit(:title, :description, :category, :how_to_apply, :company, :location, :company_url, :company_description, :tags => [])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation) unless logged_in?
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def when_posted(job)
    content_tag(:span, data: {toggle: 'tooltip', title: job.posted_at.to_s(:short)}) do
      "#{time_ago_in_words(job.posted_at)} ago"
    end.html_safe
  end

  def active_tab_class(tab, tags)
    return 'active' if tags.include?(tab)
    return 'active' if tab == 'everything' && (TagBuilder::CATEGORY_TAGS & tags).empty?
    ''
  end
end

app/views/jobs/_form.html.haml
%fieldset
  .form-group
    = f.label :title, "Job Title", class: 'control-label'
    = f.text_field :title, class: 'form-control'
  .form-group.description
    = f.label :description, "Job Description", class: 'control-label'
    = f.text_area :description, class: 'form-control wysiwyg tall'
  .form-group
    = f.label :category, "Job Category", class: 'control-label'
    = f.select :category, ['Development','Design','Management','Other'], {}, class: 'form-control'
  .form-group
    = f.label :tags, "Tags", class: 'control-label'
    = f.select :tags, ['ruby','java','php','javascript'], {}, class: 'form-control tags', multiple: true, id: 'tags'
  .form-group.instructions
    = f.label :how_to_apply, "Instructions for how to apply", class: 'control-label'
    = f.text_area :how_to_apply, class: 'form-control wysiwyg', placeholder: 'How should the candidate reach you? What should they provide?'

%fieldset
  %legend About the company
  .form-group
    = f.label :company, "Company Name", class: 'control-label'
    = f.text_field :company, class: 'form-control'
  .form-group
    = f.label :location, "Company Location", class: 'control-label'
    = f.text_field :location, class: 'form-control'
  .form-group
    = f.label :company_url, "Company Website", class: 'control-label'
    = f.text_field :company_url, class: 'form-control'
  .form-group.company-description
    = f.label :company_description, "Tell us about your company and why it rocks.", class: 'control-label'
    = f.text_area :company_description, class: 'form-control wysiwyg tall'

= fields_for :user, @job.user do |u|
  %fieldset
    %legend Your account
    - if logged_in?
      You are logged in as <b>#{current_user.email}</b>
    - else
      .row
        .col-xs-6
          .radio
            = u.label :new do
              = radio_button_tag 'account', 'new'
              Create a new account
          .form-group
            = u.label :email, "Email address", class: 'control-label'
            = u.text_field :email, class: 'form-control'
          .form-group
            = u.label :password, "Password", class: 'control-label'
            = u.password_field :password, class: 'form-control'
          .form-group
            = u.label :password_confirmation, "Confirm Password", class: 'control-label'
            = u.password_field :password_confirmation, class: 'form-control'                    
        .col-xs-6
          .radio
            = label_tag do
              = radio_button_tag 'account', 'existing'
              Log into an existing account
          .form-group
            = label_tag :email, "Email address", class: 'control-label'
            = text_field_tag :email, nil, class: 'form-control'
          .form-group
            = label_tag :password, "Password", class: 'control-label'
            = password_field_tag :password, nil, class: 'form-control'             
            
:coffeescript
  $ ->
    $( "#tags" ).select2(
      theme: "bootstrap",
      tags: #{TagBuilder.tag_list_without_categories}
    )  

    $('.wysiwyg.tall').summernote(
     height: 250
     toolbar: [     
       ['style', ['bold', 'italic', 'underline', 'clear']],
       ['font', ['strikethrough', 'superscript', 'subscript']],
       ['para', ['ul', 'ol', 'paragraph']],
     ]
    )

    $('.wysiwyg').not('.tall').summernote(
     toolbar: [     
       ['style', ['bold', 'italic', 'underline', 'clear']],
       ['font', ['strikethrough', 'superscript', 'subscript']],
       ['para', ['ul', 'ol', 'paragraph']],
     ]
    )

app/views/jobs/_job.html.haml
.job-heading
  %h1.job-title= job.title.html_safe
  %h2.job-company
    = job.company.html_safe
    &mdash;
    = job.location.html_safe
  .source
    via #{job.source}
  = render partial: 'shared/tags', locals: { job: job }
.job-description
  = job.description.squeeze(' ').html_safe
- if job.company_description.present?
  %h3.company-description Company
  = job.company_description.squeeze(' ').html_safe
- if job.how_to_apply.present?
  %h3.how-to-apply How to apply
  = job.how_to_apply.squeeze(' ').html_safe

app/views/jobs/_jobs.html.haml
- if @jobs.empty? && @today.empty?
  .text-center
    .sad
      = fa_icon 'frown-o'
    %p There&rsquo;s nothing here.
- else
  - if params[:page].blank? || params[:page] == 1
    - if @featured.present?
      %h4 Featured
      %ul.featured
        - @featured.each do |featured|
          %li= render partial: 'summary', locals: { job: featured }
    - if @today.present?
      %h4 Today
      %ul
        - @today.each do |today|
          %li= render partial: 'summary', locals: { job: today }
    - if @jobs.present?
      %h4 Earlier 
  %ul
    - @jobs.each do |job|
      %li= render partial: 'summary', locals: { job: job }

app/views/jobs/_jobs_list.html.haml
- if jobs.empty?
  .text-center
    .sad= fa_icon 'frown-o'
    %p There's nothing here.
    
- else
  %ul
    - jobs.each do |job|
      %li
        .job
          .row
            .col-sm-9
              %h2= link_to job.title, job_path(job)
            .col-sm-3
              .source.text-right= job.source
          .row
            .col-xs-8
              %h3= job.company
            .col-xs-4
              .hidden-xs
                %p.pull-right.when-posted= when_posted(job)
              .visible-xs.when-posted
                %p= when_posted(job)
          .row
            .col-xs-12
              = render partial: 'shared/tags', locals: { job: job }

  = paginate(jobs)

app/views/jobs/_summary.html.haml
.job
  .row
    .col-sm-12
      %h2= link_to job.title, job_path(job)
  .row
    .col-sm-8
      %h3
        %span.company= job.company
      .hidden-xs.source via #{job.source}
    .col-sm-4
      .hidden-xs
        %p.pull-right.when-posted= when_posted(job)
      .visible-xs.when-posted
        = when_posted(job)
      .visible-xs.source
        via #{job.source}
  .row
    .col-xs-12
      = render partial: 'shared/tags', locals: { job: job }

app/views/jobs/_why_post.html.haml
%p Why post a job on Remotely Awesome Jobs?
%ul
  %li
    Job postings are <b>totally free</b> during our beta period, no credit card required!
  %li
    Jobs posted directly on Remotely Awesome Jobs get featured prominently at the top
    of all relevant search results.
  %li
    Lots of developers already signed up for our e-mail alerts will also see your
    job in the "featured" section of the message whenever they get alerts.
  %li
    Did we mention the free part?

app/views/jobs/edit.html.haml
%h1
  - if @job.posted?
    Edit Job
  - else
    Post a Job

- unless @job.posted?  
  = render partial: 'why_post'
= render partial: 'shared/flash'
    
= form_for @job, url: job_path(@job) do |f|    
  = render partial: 'shared/job_form', locals: { f: f }
  .text-center
    - if @job.posted?
      = f.submit "Update your post", class: 'btn btn-lg btn-primary preview', data: { 'disable-with' => 'Updating...' }
    - else
      = f.submit "Preview your post", class: 'btn btn-lg btn-primary preview', data: { 'disable-with' => 'Submitting...' }

app/views/jobs/index.html.haml
.container
  .row
    .col-md-10.col-sm-9.col-xs-12
      .heading
        %h2 <b>Remotely Awesome Jobs</b> curates the best remote tech jobs across the web.
        %h3
          = number_with_delimiter Job.this_week.count
          remote jobs added this week. #{link_to "Read why we think we&rsquo;re so awesome.".html_safe, why_path}
        - if @tags.empty?
          .popular
            %i Popular tags:
            = render_tag('ruby-on-rails', @tags, @q)
            = render_tag('django', @tags, @q)
            = render_tag('objective-c', @tags, @q)
            = render_tag('java', @tags, @q)
            = render_tag('javascript', @tags, @q)
            = render_tag('php', @tags, @q)
            = render_tag('design', @tags, @q)
        = render partial: 'shared/flash'
      .navigation= render partial: 'shared/nav'
      .panel.panel-default
        .panel-heading
          = render partial: 'shared/filter', locals: { tags: @tags, q: @q }
          .row
            .col-xs-12
              = link_to "Get email alerts when matching jobs are posted".html_safe, alert_enroll_path(action: 'new', tags: @tags, q: @q)
        .panel-body
          .jobs-container
            = render partial: 'jobs'
          .text-center
            = link_to_next_page @jobs, 'Load More', remote: true, id: "load_more", class: 'btn btn-primary', data: { 'disable-with' => "<i class='fa fa-spinner fa-spin'></i> Loading...".html_safe }

app/views/jobs/index.js.haml
$('.jobs-container').append("#{escape_javascript(render 'jobs')}");
$('#load_more').replaceWith("#{escape_javascript(link_to_next_page @jobs, 'Load More', remote: true, id: 'load_more', class: 'btn btn-primary', data: { 'disable-with' => '<i class=\'fa fa-spinner fa-spin\'></i> Loading...'.html_safe })}");

app/views/jobs/new.html.haml
%h1 Post a Job

= render partial: 'why_post'
= render partial: 'shared/flash'
    
= form_for @job, url: jobs_path do |f|
  = render partial: 'shared/job_form', locals: { f: f }
  .text-center
    = f.submit "Preview your post", class: 'btn btn-lg btn-primary preview', data: { 'disable-with' => 'Submitting...' }

app/views/jobs/preview.html.haml
.preview-header Preview
= render partial: 'job', locals: { job: @job }
.apply
  .hidden-xs
    = link_to "#{fa_icon 'chevron-left'} Make more edits".html_safe, edit_job_path(@job.id), class: 'btn btn-default btn-lg'
    = link_to "Looks Great! Post this job!".html_safe, post_job_path(@job), method: :post, class: "btn btn-primary btn-lg"
  .visible-xs
    .text-center
      .row
        .col-xs-12
          %p= link_to "#{fa_icon 'chevron-left'} Back to Jobs List".html_safe, :back, class: 'btn btn-default btn-sm'
      .row
        .col-xs-12
          %p= link_to "Looks Great! Post this job!".html_safe, post_job_path(@job), method: :post, class: "btn btn-primary btn-lg", data: { 'disable-with' => 'Posting...' }

app/views/jobs/show.html.haml
.row
  .col-md-8
    = render partial: 'job', locals: { job: @job }
    .apply
      .hidden-xs.display-sm.display-md.display-lg
        .text-center
          - if @job.original_post_url.present?
            .row
              .col-xs-12
                %p= link_to "Apply on #{@job.source} #{fa_icon 'chevron-right'}".html_safe, @job.original_post_url, class: "btn btn-primary btn-lg", target: '_blank'
          .row
            .col-xs-12
              %p= link_to "#{fa_icon 'chevron-left'} Back to Jobs List".html_safe, jobs_path              
      .display-xs.hidden-sm.hidden-md.hidden-lg
        .text-center
          - if @job.original_post_url.present?
            .row
              .col-xs-12
                %p= link_to "Apply on #{@job.source} #{fa_icon 'chevron-right'}".html_safe, @job.original_post_url, class: "btn btn-primary btn-sm", target: '_blank'    
          .row
            .col-xs-12
              %p= link_to "#{fa_icon 'chevron-left'} Back to Jobs List".html_safe, jobs_path, class: 'btn btn-default btn-sm'
  .col-md-4.sidebar
    .text-center            
      .buttons
        .button= link_to "#{fa_icon 'thumb-tack'} Post a Job".html_safe, new_job_path, class: 'btn btn-info'
        .button= link_to "#{fa_icon 'twitter'} Follow Us on Twitter".html_safe, 'http://www.twitter.com/RemotelyAweJobs', class: 'btn btn-info'
        .button= link_to "#{fa_icon 'list-alt'} View More Remote Jobs".html_safe, jobs_path, class: 'btn btn-info'
        .button= link_to "#{fa_icon 'envelope'} Email alerts for jobs like this".html_safe, alert_enroll_path(action: 'new', tags: @tags, q: @q), class: "btn btn-primary"
        - if current_user && current_user.admin?
          .button= link_to "#{fa_icon 'edit'} Edit this post".html_safe, edit_admin_job_path(@job), class: "btn btn-danger"
      .similar
        %h4 Similar Posts
        - Job.similar(@job).each do |job|
          .job-mini-summary
            .job-title= link_to job.title, job_path(job)
            .job-company= job.company