config/routes.rb
class DomainConstraint
  def initialize(domain)
    @domains = [domain].flatten
  end

  def matches?(request)
    @domains.include? request.domain
  end
end

Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  constraints DomainConstraint.new(['rawsme.local', 'raws.me']) do
    get "/:id" => "shortened_links#show"
  end

  root   'jobs#index'

  get 'health_check'                      => 'health_check#index', :as => :health_check

  resources :jobs do
    member do
      get   :preview
      post  :post
      patch :pause
    end
  end
  get    '/tags/:tags'                    => 'jobs#index',     as: :tag

  post   '/alerts'                        => 'alerts#create'
  delete '/alerts/:id'                    => 'alerts#destroy', as: :alert
  get    '/alerts/new'                    => 'alerts#new'
  get    '/alerts/tags/:tags/new'         => 'alerts#new'

  get    '/unsubscribe/:token'            => 'email_addresses#unsubscribe', as: :unsubscribe

  get    '/about'                         => 'pages#about', as: :about
  get    '/why'                           => 'pages#why', as: :why

  resources :email_addresses do
    get :validate
  end
  resources :filter_tags
  resources :users
  resource  :session
  resources :password_resets
  resources :validations

  namespace :admin do
    resources :jobs
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :uuid             not null, primary key
#  created_at           :datetime
#  updated_at           :datetime
#  email                :string           not null
#  password_digest      :string           not null
#  password_reset_token :string
#  validation_token     :string
#  email_validated_at   :datetime
#  admin                :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  has_secure_password
  has_secure_token :password_reset_token
  has_secure_token :validation_token

  validates_presence_of :email
  validates_uniqueness_of :email, case_sensitive: false
  validates_presence_of :password
  validates_length_of :password, minimum: 6, allow_blank: true,
   message: 'is too short (minimum is 6 characters).'

  has_many :jobs

  after_create :validate_email!
  after_create :send_notice

  def email_validated!
    touch(:email_validated_at)
  end

  def email_validated?
    self.email_validated_at.present?
  end

  def validate_email!
    self.regenerate_validation_token
    UserMailer.validate(self.id).deliver_later
  end

  def defaults_from_previous_job
    most_recent_job = self.jobs.order('created_at desc').limit(1).first
    return {} if most_recent_job.nil?
    {
      company: most_recent_job.company,
      location: most_recent_job.location,
      company_url: most_recent_job.company_url,
      company_description: most_recent_job.company_description,
      how_to_apply: most_recent_job.how_to_apply
    }
  end


  private

  def send_notice
    NoticeMailer.new_user_signup(self.id).deliver_later(queue: :low)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to jobs_path, notice: "Welcome aboard! Your account has been created."
    else
      flash[:error] = "Invalid user information: #{@user.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def show
    render_404 and return unless params[:id] == current_user.id
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def job_list_action(user,job)
    if !user.email_validated?
      "Awaiting Email Address Validation"
    else
      if job.posted?
        (link_to "#{fa_icon 'pause'} Pause".html_safe, pause_job_path(job), method: :patch, class: 'btn btn-xs btn-default') + ' ' +
        (link_to "#{fa_icon 'pencil-square-o'} Edit Post".html_safe, edit_job_path(job), class: 'btn btn-xs btn-default')
      else
        (link_to "#{fa_icon 'play'} Post Now".html_safe, post_job_path(job), method: :post, class: 'btn btn-xs btn-default') + ' ' +
        (link_to "#{fa_icon 'trash'} Delete".html_safe, job_path(job), method: :delete, class: 'btn btn-xs btn-danger delete-job', data: { title: job.title })
      end
    end
  end

  def dashboard_message(user)
    if !user.email_validated?
      if user.jobs.pending.present?
        "You still need to validate your email address before your jobs can be posted on the site. #{link_to 'Resend verification now.', validations_path, method: :post}".html_safe
      else
        "You still need to validate your email address. #{link_to 'Resend verification now.', validations_path, method: :post}".html_safe
      end
    else
      if user.jobs.paused.present?
        "You have job posts which are paused. Click <b>Post Now</b> below to make them appear on the site.".html_safe
      else
        nil
      end
    end
  end
end

app/views/users/new.html.haml
%h1 Glad to meet you!
= render partial: 'shared/flash'
%p
  Welcome aboard. Signing up will give you the ability to post jobs to the
  job board. Just let us know how to reach you and you&rsquo;ll be on your way! 
.row
  .col-xs-12
    = form_for @user do |f|
      .form-group
        = f.label :email
        = f.text_field :email, class: 'input input-lg form-control'
      .form-group
        = f.label :password
        = f.password_field :password, class: 'input input-lg form-control'
      .form-group
        = f.label :password_confirmation, "Password one more time (just to be sure)"
        = f.password_field :password_confirmation, class: 'input input-lg form-control'                  
      .form-group
        .text-center= submit_tag "Sign me up!", class: 'btn btn-lg btn-primary', data: { 'disable-with' => "Creating your account..." }

app/views/users/show.html.haml
%h1 Your Account
You are currently signed in as <b>#{current_user.email}</b>

- message = dashboard_message(current_user)
- if message.present?
  .message
    .alert.alert-danger= message
  
.message= render partial: 'shared/flash'
    
%legend Posted Jobs
- if current_user.jobs.present?
  %table.table.table-condensed
    %thead
      %tr
        %th Job Title
        %th Posted at
        %th Expires at
        %th Status
        %th 
    - current_user.jobs.each do |job|
      %tr
        %td= link_to job.title, job_path(job)
        %td
          - if job.posted? && job.posted_at.present?
            = job.posted_at.to_s(:mini_date_time)
          - else
            Never
        %td
          - if job.posted? && job.expires_at.present?
            = job.expires_at.to_s(:mini_date_time)          
        %td= job.status.humanize
        %td
          .pull-right= job_list_action(current_user, job)
- else
  (No jobs posted yet)

%legend Payment Information
No payment information on your account.
  
.actions.text-center
  = link_to "#{fa_icon 'thumb-tack'} Post a job".html_safe, new_job_path, class: "btn btn-lg btn-default"
  = link_to "#{fa_icon 'sign-out'} Sign out".html_safe, session_path, method: :delete, class: "btn btn-lg btn-primary"

:coffeescript
  $ ->
    $('.delete-job').on 'click', (e)->
      e.preventDefault()
      $clicked = $(e.target)
      title = $clicked.data('title')
      bootbox.confirm "Delete the post for <b>" + title + "</b>?", (result)->
        if result
          $clicked.unbind "click"
          $clicked.get(0).click()
      false  