config/routes.rb
class DomainConstraint
  def initialize(domain)
    @domains = [domain].flatten
  end

  def matches?(request)
    @domains.include? request.domain
  end
end

Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'

  constraints DomainConstraint.new(['rawsme.local', 'raws.me']) do
    get "/:id" => "shortened_links#show"
  end

  root   'jobs#index'

  get 'health_check'                      => 'health_check#index', :as => :health_check

  resources :jobs do
    member do
      get   :preview
      post  :post
      patch :pause
    end
  end
  get    '/tags/:tags'                    => 'jobs#index',     as: :tag

  post   '/alerts'                        => 'alerts#create'
  delete '/alerts/:id'                    => 'alerts#destroy', as: :alert
  get    '/alerts/new'                    => 'alerts#new'
  get    '/alerts/tags/:tags/new'         => 'alerts#new'

  get    '/unsubscribe/:token'            => 'email_addresses#unsubscribe', as: :unsubscribe

  get    '/about'                         => 'pages#about', as: :about
  get    '/why'                           => 'pages#why', as: :why

  resources :email_addresses do
    get :validate
  end
  resources :filter_tags
  resources :users
  resource  :session
  resources :password_resets
  resources :validations

  namespace :admin do
    resources :jobs
  end
end

app/views/shared/_filter.html.haml
.row
  .col-xs-12
    .filter-label Filters
  
.search-filter
  .row
    .col-xs-12
      - if q.present?
        %b Searched For:
        = q
        = link_to remove_search_query_url(request.path) do
          = fa_icon 'times-circle'
      - else
        = form_tag request.path, method: :get do
          = hidden_field_tag 'tags', tags.join('+'), multiple: true
          .input-group
            = text_field_tag :q, nil, class: 'form-control', placeholder: 'Search for...'
            .input-group-btn
              %button.btn.btn-primary{ type: 'submit' }
                #{fa_icon 'search'} Search

.tag-filter.form-inline
  - if tags.present?
    - tags.each do |tag|
      %span.label.label-tag{ class: "label-#{TagBuilder.tag_type(tag.to_s)}-tag"}
        = tag.to_s
        = link_to(filter_tag_path(tag.to_s, q: @q), method: :delete) do
          = fa_icon 'times-circle'
  = link_to "#{fa_icon 'plus'} Add a tag filter".html_safe, nil, id: 'add-tag'
  %span.hidden#add-tag-field-wrapper
    = form_tag filter_tags_path do
      = text_field_tag :tag_name, nil, class: 'form-control input-xs', id: 'add-tag-field', placeholder: "Add a tag".html_safe
      .hidden
        = submit_tag
  
:coffeescript  
  $ ->
    $('#add-tag').on 'click', (e)->
      e.preventDefault()
      $('#add-tag').addClass 'hidden'
      $('#add-tag-field-wrapper').removeClass 'hidden'

    tags = new Bloodhound(
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('tag')
      queryTokenizer: Bloodhound.tokenizers.whitespace
      local: #{tag_autocomplete_options(tags)}
    ) 
    tags.initialize()
      
    $('#add-tag-field').typeahead({
      minlength: 3,
      highlight: true
      },{
      displayKey: 'tag'
      source: tags.ttAdapter()
      }
    )

app/views/shared/_flash.html.haml
- if flash[:notice].present?
  .alert.alert-info= flash[:notice]
- elsif flash[:error].present?
  .alert.alert-danger= flash[:error]

app/views/shared/_ga.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65254538-2', 'auto');
  ga('send', 'pageview');

app/views/shared/_job_form.html.haml
%fieldset
  .form-group
    = f.label :title, "Job Title", class: 'control-label'
    = f.text_field :title, class: 'form-control'
  .form-group.description
    = f.label :description, "Job Description", class: 'control-label'
    = f.text_area :description, class: 'form-control wysiwyg tall'
  .form-group
    = f.label :category, "Job Category", class: 'control-label'
    = f.select :category, ['Development','Design','Management','Other'], {}, class: 'form-control'
  .form-group
    = f.label :tags, "Tags", class: 'control-label'
    = f.select :tags, ['ruby','java','php','javascript'], {}, class: 'form-control tags', multiple: true, id: 'tags'
  .form-group.instructions
    = f.label :how_to_apply, "Instructions for how to apply", class: 'control-label'
    = f.text_area :how_to_apply, class: 'form-control wysiwyg', placeholder: 'How should the candidate reach you? What should they provide?'

%fieldset
  %legend About the company
  .form-group
    = f.label :company, "Company Name", class: 'control-label'
    = f.text_field :company, class: 'form-control'
  .form-group
    = f.label :location, "Company Location", class: 'control-label'
    = f.text_field :location, class: 'form-control'
  .form-group
    = f.label :company_url, "Company Website", class: 'control-label'
    = f.text_field :company_url, class: 'form-control'
  .form-group.company-description
    = f.label :company_description, "Tell us about your company and why it rocks.", class: 'control-label'
    = f.text_area :company_description, class: 'form-control wysiwyg tall'

= fields_for :user, @job.user do |u|
  %fieldset
    %legend Your account
    - if logged_in?
      You are signed in as <b>#{current_user.email}</b>
    - else
      .row
        .col-xs-6.spec-new
          .radio
            = u.label :new do
              = radio_button_tag 'account', 'new'
              Create a new account
          .form-group
            = u.label :email, "Email address", class: 'control-label'
            = u.text_field :email, class: 'form-control'
          .form-group
            = u.label :password, "Password", class: 'control-label'
            = u.password_field :password, class: 'form-control'
          .form-group
            = u.label :password_confirmation, "Confirm Password", class: 'control-label'
            = u.password_field :password_confirmation, class: 'form-control'                    
        .col-xs-6.spec-existing
          .radio
            = label_tag do
              = radio_button_tag 'account', 'existing'
              Sign in to an existing account
          .form-group
            = label_tag :email, "Email address", class: 'control-label'
            = text_field_tag :email, nil, class: 'form-control'
          .form-group
            = label_tag :password, "Password", class: 'control-label'
            = password_field_tag :password, nil, class: 'form-control'             
            
:coffeescript
  $ ->
    $( "#tags" ).select2(
      theme: "bootstrap",
      tags: #{TagBuilder.tag_list_without_categories}
    )  

    $('.wysiwyg.tall').summernote(
     height: 250
     toolbar: [     
       ['style', ['bold', 'italic', 'underline', 'clear']],
       ['font', ['strikethrough', 'superscript', 'subscript']],
       ['para', ['ul', 'ol', 'paragraph']],
     ]
    )

    $('.wysiwyg').not('.tall').summernote(
     toolbar: [     
       ['style', ['bold', 'italic', 'underline', 'clear']],
       ['font', ['strikethrough', 'superscript', 'subscript']],
       ['para', ['ul', 'ol', 'paragraph']],
     ]
    )

app/views/shared/_nav.html.haml
-# For big screens
-# Sidebar
%nav.navmenu.navmenu-inverse.navmenu-fixed-left.offcanvas-xs.nobar
  = render partial: 'shared/side_nav'

-# For small screens
-# Header
%nav.navbar.navbar-fixed-top.navbar-inverse.visible-xs
  = render partial: 'shared/top_nav'
-# Sidebar
%nav.navmenu.navmenu-inverse.navmenu-fixed-left.offcanvas#navmenu.nobar
  = render partial: 'shared/side_nav'

app/views/shared/_side_nav.html.haml
.hidden-xs
  = link_to root_path, class: "navmenu-brand" do
    = image_tag 'remotely-awesome-logo-white.png', class: 'logo'
%ul.nav.navmenu-nav
  %li{ class: active_tab_class('everything', @tags) }
    = link_to "Recent", jobs_path, class: 'category-link'
  %li{ class: active_tab_class('development', @tags) }
    = link_to "Develop", tag_path('development'), class: 'category-link'
  %li{ class: active_tab_class('design', @tags) }
    = link_to "Design", tag_path('design'), class: 'category-link'
  %li{ class: active_tab_class('management', @tags) }
    = link_to "Manage", tag_path('management'), class: 'category-link'
  %li{ class: active_tab_class('other', @tags) }
    = link_to "Other", tag_path('other'), class: 'category-link'

.buttons
  .text-center
    = link_to "#{fa_icon 'thumb-tack'} Post a Job".html_safe, new_job_path, class: 'btn btn-primary'
    = link_to "#{fa_icon 'twitter'} Follow Us".html_safe, 'http://www.twitter.com/RemotelyAweJobs', class: 'btn btn-twitter'
    = link_to "#{fa_icon 'envelope'} Get Alerts".html_safe, alert_enroll_path(action: 'new', tags: @tags, q: @q), class: 'btn btn-info'
    .session
      - if logged_in?    
        = link_to "#{fa_icon 'home'} Your account".html_safe, user_path(current_user)
      - else
        = link_to "#{fa_icon 'sign-in'} Sign in".html_safe, new_session_path
        
.ceres
  .text-center
    .project
      A Project By    
    %a{ href: 'http://www.cereslogic.com' }    
      = image_tag 'ceres-logic-logo-bw-white.png', class: 'ceres-logo'

.about
  .text-center
    = link_to "#{fa_icon 'info-circle'} About".html_safe, about_path
  

app/views/shared/_tag_filter.html.haml
.tag-filter.form-inline
  - if tags.present?
    - tags.each do |tag|
      %span.label.label-tag{ class: "label-#{TagBuilder.tag_type(tag.to_s)}-tag"}
        = tag.to_s
        = link_to(filter_tag_path(tag.to_s), method: :delete) do
          = fa_icon 'times-circle'
  = link_to "#{fa_icon 'plus'}".html_safe, nil, id: 'add-tag'
  %span.hidden#add-tag-field-wrapper
    = form_tag filter_tags_path do
      = text_field_tag :tag_name, nil, class: 'form-control input-xs', id: 'add-tag-field', placeholder: "Add a tag".html_safe
      .hidden
        = submit_tag
  
:coffeescript  
  $ ->
    $('#add-tag').on 'click', (e)->
      e.preventDefault()
      $('#add-tag').addClass 'hidden'
      $('#add-tag-field-wrapper').removeClass 'hidden'

    tags = new Bloodhound(
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('tag')
      queryTokenizer: Bloodhound.tokenizers.whitespace
      local: #{tag_autocomplete_options(tags)}
    ) 
    tags.initialize()
      
    $('#add-tag-field').typeahead({
      minlength: 3,
      highlight: true
      },{
      displayKey: 'tag'
      source: tags.ttAdapter()
      }
    )

app/views/shared/_tags.html.haml
.tags
  - job.grouped_tags.uniq.each do |tag|
    .no-break
      %span.label.label-tag{ class: "label-#{TagBuilder.tag_type(tag.to_s)}-tag" }
        = link_to(tag.to_s, add_tag_url(@tags, tag.to_s, @q))

app/views/shared/_top_header.html.haml
.navbar-header
  = link_to root_path, class: "navbar-brand" do
    = image_tag 'remotely-awesome-logo-white-horizontal.png', class: 'horizontal-logo'

app/views/shared/_top_nav.html.haml
%button.navbar-toggle{type: "button", data: {toggle: "offcanvas", target: "#navmenu"}}
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar
= render partial: 'shared/top_header'  